# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170419_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('width', models.IntegerField(default=960)),
                ('height', models.IntegerField(default=500)),
                ('padding_top', models.IntegerField(default=20)),
                ('padding_right', models.IntegerField(default=100)),
                ('padding_bottom', models.IntegerField(default=100)),
                ('padding_left', models.IntegerField(default=100)),
                ('x_indicator', models.CharField(blank=True, max_length=255, null=True)),
                ('y_indicator', models.CharField(blank=True, max_length=255, null=True)),
                ('z_indicator', models.CharField(blank=True, max_length=255, null=True)),
                ('c_indicator', models.CharField(blank=True, max_length=255, null=True)),
                ('sort', models.CharField(blank=True, max_length=255, null=True)),
                ('y_maximum', models.CharField(blank=True, max_length=255, null=True)),
                ('y_maximum_value', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('x_label', models.CharField(blank=True, max_length=255, null=True)),
                ('y_label', models.CharField(blank=True, max_length=255, null=True)),
                ('x_text_rotation', models.IntegerField(default=45)),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dataset')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
