# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170421_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisation',
            name='colour',
            field=models.CharField(blank=True, default='#e84439', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visualisation',
            name='y_maximum',
            field=models.CharField(blank=True, default='auto', max_length=255, null=True),
        ),
    ]
