# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170424_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='x_maximum',
            field=models.CharField(blank=True, default='auto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='x_maximum_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=99, null=True),
        ),
    ]
