# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visualisation_label_significant_digits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisation',
            name='label_significant_digits',
        ),
        migrations.AddField(
            model_name='visualisation',
            name='label_format',
            field=models.CharField(default=',.2f', max_length=255),
        ),
    ]
