# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170425_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='unit_divisor',
            field=models.IntegerField(default=1),
        ),
    ]
