# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170425_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisation',
            name='exterior_arc_percent',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='interior_arc_percent',
        ),
    ]
