# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-26 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170425_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='sep',
            field=models.CharField(default='\t', max_length=1),
        ),
    ]
