# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170426_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='filter_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='filter_selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
