# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170427_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisation',
            name='filter_by',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
