# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170427_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='legend_position',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
