# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_visualisation_legend_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisation',
            name='legend_position',
            field=models.CharField(default='tr', max_length=2),
        ),
    ]
