# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170428_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='y_axis_ticks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
