# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170522_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='inject_css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
