# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 17:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_visualisation_inject_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualisation',
            name='bubble_maximum',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='bubble_minimum',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='c_indicator',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='chart_type',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='filter_by',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='filter_selection',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='group_by',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='height',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='inject_css',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='label_font_size',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='label_format',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='labels_on_chart',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='legend_position',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='padding_bottom',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='padding_left',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='padding_right',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='padding_top',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='unit_divisor',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='width',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='x_indicator',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='x_label',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='x_maximum',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='x_maximum_value',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='x_text_rotation',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='y_axis_ticks',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='y_indicator',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='y_label',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='y_maximum',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='y_maximum_value',
        ),
        migrations.RemoveField(
            model_name='visualisation',
            name='z_indicator',
        ),
        migrations.AddField(
            model_name='visualisation',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
