# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20170609_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='chart_type',
            field=models.CharField(default='bar', max_length=255),
            preserve_default=False,
        ),
    ]
