# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_visualisation_chart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='configuration_flat',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
