# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_visualisation_configuration_flat'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualisation',
            name='filter_by',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='filter_selection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='height',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='padding_bottom',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='padding_left',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='padding_right',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='padding_top',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='sort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='sort_direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visualisation',
            name='width',
            field=models.IntegerField(default=960),
        ),
    ]
