# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_visualisation_unit_divisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisation',
            name='padding_bottom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visualisation',
            name='padding_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visualisation',
            name='padding_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visualisation',
            name='padding_top',
            field=models.IntegerField(default=0),
        ),
    ]
