# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20170619_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisation',
            name='padding_top',
            field=models.IntegerField(default=0),
        ),
    ]
