# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170619_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualisation',
            name='padding_bottom',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='visualisation',
            name='padding_left',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='visualisation',
            name='padding_right',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='visualisation',
            name='padding_top',
            field=models.IntegerField(default=10),
        ),
    ]
